# Generated by Django 5.2 on 2025-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='Almacena el ID del archivo subido a Google Drive.', max_length=128, null=True, verbose_name='ID en Drive'),
        ),
    ]
